# Generated by Django 4.0.6 on 2022-07-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Monthly', 'Monthly'), ('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Lifetime', 'Lifetime'), ('Signal only', 'Signal only')], max_length=200)),
                ('quantity', models.IntegerField(default=3)),
                ('price', models.FloatField(default=0)),
                ('saving', models.FloatField(default=0)),
                ('tax', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
            },
        ),
    ]
