# Generated by Django 4.0.6 on 2022-07-08 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_tradeidea'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeidea',
            name='date_sent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
