# Generated by Django 4.0.6 on 2022-07-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_tradeidea_date_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeidea',
            name='status',
            field=models.CharField(choices=[('Not triggered', 'Not triggered'), ('Hit tp', 'Hit tp'), ('Hit sl', 'Hit sl')], default='Not triggered', max_length=25),
        ),
    ]
