# Generated by Django 4.0.6 on 2022-07-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_tradeidea_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeidea',
            name='order_type',
            field=models.CharField(choices=[('Sell', 'Sell'), ('Sell Stop', 'Sell Stop'), ('Sell Limit', 'Sell Limit'), ('Buy', 'Buy'), ('Buy Stop', 'Buy Stop'), ('Buy Limit', 'Buy Limit')], default='Sell', max_length=50),
        ),
        migrations.AddField(
            model_name='tradeidea',
            name='timeframe',
            field=models.CharField(choices=[('5M', '5M'), ('15M', '15M'), ('30M', '30M'), ('H1', 'H1'), ('H4', 'H4'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='15M', max_length=20),
        ),
    ]
