# Generated by Django 4.0.6 on 2022-07-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_tradeidea_order_type_tradeidea_timeframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeidea',
            name='entry',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='tradeidea',
            name='sl',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='tradeidea',
            name='status',
            field=models.CharField(choices=[('Not triggered', 'Not triggered'), ('Hit tp', 'Hit tp'), ('Hit sl', 'Hit sl'), ('Pending', 'Pending')], default='Pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='tradeidea',
            name='tp1',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='tradeidea',
            name='tp2',
            field=models.CharField(blank=True, default='0', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tradeidea',
            name='tp3',
            field=models.CharField(blank=True, default='0.', max_length=20, null=True),
        ),
    ]
