# Generated by Django 4.0.6 on 2022-07-21 10:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_alter_tradeidea_entry_alter_tradeidea_sl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedpackage',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
