# Generated by Django 4.0.6 on 2022-07-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_alter_selectedpackage_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedpackage',
            name='email',
            field=models.EmailField(default='amir.cpu@gmail.com', max_length=254),
        ),
    ]
