# Generated by Django 4.0.6 on 2022-07-14 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=150)),
                ('email', models.EmailField(max_length=255)),
                ('number', models.CharField(max_length=15)),
                ('message', models.TextField(default='')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
