# Generated by Django 4.0.6 on 2022-07-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordmodel',
            name='email',
            field=models.EmailField(default='amir.cpu@gmail.com', max_length=254),
        ),
    ]
