# Generated by Django 4.0.6 on 2022-08-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('when', models.DateTimeField()),
                ('status', models.CharField(choices=[('Done', 'Done'), ('Upcoming', 'Upcoming')], max_length=20)),
            ],
        ),
    ]
