# Generated by Django 4.0.6 on 2022-07-14 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_lessonmodel_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Quizes', 'verbose_name_plural': 'Quizes'},
        ),
    ]
