# Generated by Django 4.0.6 on 2022-07-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_alter_quiz_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonmodel',
            name='point',
            field=models.FloatField(default=3.39),
        ),
    ]
