# Generated by Django 4.0.6 on 2022-07-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_lessonmodel_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
