# Generated by Django 4.0.6 on 2022-08-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_quiz_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonmodel',
            name='satus',
            field=models.CharField(choices=[('Done', 'Done'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
