# Generated by Django 4.0.6 on 2022-08-05 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_lessonmodel_satus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonmodel',
            old_name='satus',
            new_name='status',
        ),
    ]
